### ISSUE TITLE
EAN13 barcode length issue

### ISSUE THREAD

**Issue by niladri6** [barbecue-sf/code#1]
EAN13 Barcode Length should be 12 or 13 characters long.

net.sourceforge.barbecue.BarcodeException: Invalid data length     at net.sourceforge.barbecue.linear.upc.UPCABarcode.<init>(Unknown Source)     at net.sourceforge.barbecue.linear.upc.UPCABarcode.<init>(Unknown Source)     at net.sourceforge.barbecue.linear.ean.EAN13Barcode.<init>(Unknown Source)     at net.sourceforge.barbecue.BarcodeFactory.createEAN13(Unknown Source)

**Comment by niladri6** [comment]
please fix it

**Comment by keilw** [comment]
Please provide a PR. Normally a project that has not seen any code commit in 7-8 years would long be archived, but as soon as there are still interested users and those willing to raise PRs no problem keeping it active.
